[package]
name = "file_interaction_actor"
version = "0.1.0"
edition.workspace = true
license.workspace = true
description = "File interaction actor for reading and editing files"
repository.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen-rt = { version = "0.43", features = ["bitflags"] }
toml = "0.8"

serde.workspace = true
serde_json.workspace = true

file_interaction = { path = "../file_interaction" }
hive_actor_utils.workspace = true

[package.metadata.component.target.dependencies]
"hive:actor" = { path = "../../../../crates/hive_actor_bindings/wit" }
