[package]
name = "send_message"
version = "0.1.0"
edition.workspace = true
license.workspace = true
description = "Message passing actor for agent-to-agent communication"
repository.workspace = true
readme.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wasmind_actor_utils.workspace = true
delegation_network_common_types = { path = "../common_types" }
serde.workspace = true
serde_json = "1"
toml.workspace = true
wit-bindgen-rt.workspace = true

[package.metadata.component.target.dependencies]
"wasmind:actor" = { path = "../../../../crates/wasmind_actor_bindings/wit" }