[package]
name = "copilot"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = "3.5.0"
base64 = "0.22.1"
crossbeam = "0.8.4"
etcetera = "0.10.0"
genai = "0.3.1"
image = "0.25.6"
rdev = { version = "0.5.3", features = ["unstable_grab"] }
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.45.0", features = ["rt-multi-thread", "time"] }
snafu = "0.8.5"
toml = "0.8.22"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
xcap = "0.5.2"
futures = "0.3.31"
crossterm = "0.29.0"
ratatui = "0.29.0"
