# Automatically approve non-whitelisted commands (default: false)
# When false, non-whitelisted commands require user confirmation
# When true, all commands are auto-approved (use with caution)
auto_approve_commands = false

# Commands that can be executed without user confirmation
# Common safe commands are whitelisted by default
whitelisted_commands = [
    "ls",
    "pwd",
    "echo",
    "cat",
    "grep",
    "rg",
    "find",
    "git",
    "cargo",
    "npm",
    "node",
    "python",
    "pip",
    "which",
    "date",
    "whoami",
    "uname",
    "head",
    "tail",
    "wc",
    "sort",
    "uniq",
    "diff",
    "tree"
]

[key_bindings]
clear_defaults = false

[key_bindings.bindings]
"cmd-alt-w" = "CaptureWindow"
"cmd-alt-y" = "CaptureClipboard"
"cmd-alt-a" = "Assist"
"cmd-alt-m" = "ToggleRecordMicrophone"
"ctrl-c" = "Exit"

# HIVE Multi-Agent System Configuration
[hive]

# Default model configuration - used as fallback when model_name or litellm_params are not specified for specific models
[hive.default_model]
model_name = "gpt-4o"

[hive.default_model.litellm_params]
model = "openai/gpt-4o"
api_key = "os.environ/OPENAI_API_KEY"

# Main Manager configuration
[hive.main_manager_model]
system_prompt = """FILLER

{% if task -%}
<assigned_task>
{{ task }}
</assigned_task>
{% endif %}

<system_info>
Current date and time: {{ current_datetime }}
System: {{ os }} ({{ arch }})
Working directory: {{ cwd }}
</system_info>

{% if files.count > 0 -%}
<read_and_edited_files>
{% for file in files.list -%}
<file path="{{ file.path }}">
{{ file.content }}
</file>
{% endfor %}
</read_and_edited_files>
{% endif %}

{% if plan.exists -%}
<plan title="{{ plan.data.title }}">
{% for task in plan.data.tasks -%}
<task status="{{ task.status }}">{{ task.description }}</task>
{% endfor %}
</plan>
{% endif %}

{% if agents.count > 0 -%}
<spawned_agents>
{% for agent in agents.list -%}
<agent id="{{ agent.id }}" role="{{ agent.role }}" status="{{ agent.status }}">
<task>{{ agent.task }}</task>
</agent>
{% endfor %}
</spawned_agents>
{% endif %}
"""

# Sub-Manager configuration (for managers spawned by other managers)
[hive.sub_manager_model]
system_prompt = """FILLER"""

# Worker configuration
[hive.worker_model]
system_prompt = """FILLER"""
