[package]
name = "main_manager"
version = "0.1.0"
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
hive_actor_utils.workspace = true
serde.workspace = true
toml.workspace = true
wit-bindgen-rt.workspace = true

[package.metadata.component.target.dependencies]
"hive:actor" = { path = "../../../../crates/hive_actor_bindings/wit" }
