[package]
name = "delegation_network_common_types"
version = "0.1.0"
edition.workspace = true
license.workspace = true
description = "Common types and structures for delegation network actors"
repository.workspace = true
readme.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
wasmind_actor_utils.workspace = true