actor_id = "wasmind_code_with_experts:file_interaction_with_approval"

[dependencies.hcwe_approve]
source = { path = "../../crates/approve" }

[dependencies.hcwe_request_changes]
source = { path = "../../crates/request_changes" }
