starting_actors = ["delegation_network_coordinator"]

##############################
# TUI Specific Config ########
##############################

[tui.dashboard.key_bindings]
"ctrl-c" = "Exit"

[tui.chat.key_bindings]
"ctrl-a" = "Assist"

[tui.graph.key_bindings]
"shift-down" = "SelectDown"
"shift-up" = "SelectUp"

##############################
# Actors Config ##############
##############################

[actors.delegation_network_coordinator]
source = { path = "/Users/silasmarvin/github/hive/actors/delegation_network", package = "crates/delegation_network_coordinator" }

[actor_overrides.main_manager_assistant.config]
model_name = "horizon-beta"

[actor_overrides.sub_manager_assistant.config]
model_name = "horizon-beta"

[actor_overrides.worker_assistant.config]
model_name = "horizon-beta"

[actor_overrides.check_health_assistant.config]
model_name = "horizon-beta"

##############################
# LiteLLM Config #############
##############################

[litellm]
image = "ghcr.io/berriai/litellm:main-latest"
port = 4000
container_name = "hive-litellm"

[[litellm.models]]
model_name = "gpt-4o"

[litellm.models.litellm_params]
model = "openai/gpt-4o"
api_key = "os.environ/OPENAI_API_KEY"

[[litellm.models]]
model_name = "horizon-beta"

[litellm.models.litellm_params]
model = "openrouter/openrouter/horizon-beta"
api_key = "os.environ/OPENROUTER_API_KEY"

# [[litellm.models]]
# model_name = "qwen3-480b"
#
# [litellm.models.litellm_params]
# model = "cerebras/qwen-3-coder-480b"
# api_key = "os.environ/CEREBRAS_API_KEY"
