starting_actors = ["main_manager_assistant", "spawn_agent", "send_message", "planner", "wait"]

##############################
# TUI Specific Config ########
##############################

[tui.dashboard.key_bindings]
"ctrl-c" = "Exit"

[tui.chat.key_bindings]
"ctrl-a" = "Assist"

[tui.graph.key_bindings]
"shift-down" = "SelectDown"
"shift-up" = "SelectUp"

##############################
# Actors Config ##############
##############################

[actors.delegation_network_main_manager]
source = { path = "/Users/silasmarvin/github/hive/actors/delegation_network", package = "crates/delegation_network_coordinator" }

[actor_overrides.main_manager_assistant.config]
model_name = "gpt-4o"

[actor_overrides.sub_manager_assistant.config]
model_name = "gpt-4o"

[actor_overrides.worker_assistant.config]
model_name = "gpt-4o"

##############################
# LiteLLM Config #############
##############################

[litellm]
image = "ghcr.io/berriai/litellm:main-latest"
port = 4000
container_name = "hive-litellm"

[[litellm.models]]
model_name = "gpt-4o"

[litellm.models.litellm_params]
model = "openai/gpt-4o"
api_key = "os.environ/OPENAI_API_KEY"
