[package]
name = "complete"
version = "0.1.0"
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
hive_actor_utils.workspace = true
serde.workspace = true
serde_json = "1"
wit-bindgen-rt.workspace = true
uuid.workspace = true

[package.metadata.component.target.dependencies]
"hive:actor" = { path = "../../../../crates/hive_actor_bindings/wit" }

[profile.release]
opt-level = "s"