[package]
name = "wasmind_actor_bindings"
version = "0.1.0"

description.workspace = true
repository.workspace = true
readme.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
wit-bindgen-rt = { workspace = true }

[lib]
