[package]
name = "check_health"
version = "0.1.0"
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
hive_actor_utils.workspace = true
serde.workspace = true
serde_json = "1"
toml.workspace = true
wit-bindgen-rt.workspace = true
uuid = { version = "1.0", features = ["v4"] }
delegation_network_common_types = { path = "../common_types" }

[package.metadata.component.target.dependencies]
"hive:actor" = { path = "../../../../crates/hive_actor_bindings/wit" }