[package]
name = "file_interaction"
version = "0.1.0"
edition.workspace = true
license.workspace = true
description = "Pure Rust library for file interaction operations"
repository.workspace = true
authors.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
wasmind_actor_utils.workspace = true

similar = "2.7"

[dev-dependencies]
tempfile = "3"
