// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod hive {
    pub mod actor {
        /// =================================================================
        /// CAPABILITY INTERFACES
        /// Each interface represents a distinct capability that can be
        /// optionally provided to actors
        /// =================================================================
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod messaging {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            #[allow(unused_unsafe, clippy::all)]
            /// Broadcasts a message to all other actors in the system
            pub fn broadcast(message_type: &str, payload: &[u8]) -> () {
                unsafe {
                    let vec0 = message_type;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let vec1 = payload;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "hive:actor/messaging@0.1.0")]
                    unsafe extern "C" {
                        #[link_name = "broadcast"]
                        fn wit_import2(_: *mut u8, _: usize, _: *mut u8, _: usize);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                    ) {
                        unreachable!()
                    }
                    unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1) };
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod hive {
        pub mod actor {
            /// =================================================================
            /// INTERFACE 1: Core Actor Model
            /// This interface defines the essential types and behaviors required
            /// to create a stateful, message-driven actors.
            /// =================================================================
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod actor {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                /// An envelope that wraps every message passed between actors.
                /// It provides context about the message's origin.
                #[derive(Clone)]
                pub struct MessageEnvelope {
                    /// The unique identifier of the message type
                    pub message_type: _rt::String,
                    /// The unique identifier of the actor that sent the message.
                    pub from_actor_id: _rt::String,
                    /// The scope in which the sending actor was operating.
                    pub from_scope: _rt::String,
                    /// The raw, serialized message data. The format (e.g., JSON)
                    /// is determined by the sending actor's implementation.
                    pub payload: _rt::Vec<u8>,
                }
                impl ::core::fmt::Debug for MessageEnvelope {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("MessageEnvelope")
                            .field("message-type", &self.message_type)
                            .field("from-actor-id", &self.from_actor_id)
                            .field("from-scope", &self.from_scope)
                            .field("payload", &self.payload)
                            .finish()
                    }
                }
                /// Represents a stateful actor instance. Actor authors must provide
                /// an implementation for this resource.
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct Actor {
                    handle: _rt::Resource<Actor>,
                }
                type _ActorRep<T> = Option<T>;
                impl Actor {
                    /// Creates a new resource from the specified representation.
                    ///
                    /// This function will create a new resource handle by moving `val` onto
                    /// the heap and then passing that heap pointer to the component model to
                    /// create a handle. The owned handle is then returned as `Actor`.
                    pub fn new<T: GuestActor>(val: T) -> Self {
                        Self::type_guard::<T>();
                        let val: _ActorRep<T> = Some(val);
                        let ptr: *mut _ActorRep<T> = _rt::Box::into_raw(
                            _rt::Box::new(val),
                        );
                        unsafe { Self::from_handle(T::_resource_new(ptr.cast())) }
                    }
                    /// Gets access to the underlying `T` which represents this resource.
                    pub fn get<T: GuestActor>(&self) -> &T {
                        let ptr = unsafe { &*self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    /// Gets mutable access to the underlying `T` which represents this
                    /// resource.
                    pub fn get_mut<T: GuestActor>(&mut self) -> &mut T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_mut().unwrap()
                    }
                    /// Consumes this resource and returns the underlying `T`.
                    pub fn into_inner<T: GuestActor>(self) -> T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.take().unwrap()
                    }
                    #[doc(hidden)]
                    pub unsafe fn from_handle(handle: u32) -> Self {
                        Self {
                            handle: unsafe { _rt::Resource::from_handle(handle) },
                        }
                    }
                    #[doc(hidden)]
                    pub fn take_handle(&self) -> u32 {
                        _rt::Resource::take_handle(&self.handle)
                    }
                    #[doc(hidden)]
                    pub fn handle(&self) -> u32 {
                        _rt::Resource::handle(&self.handle)
                    }
                    #[doc(hidden)]
                    fn type_guard<T: 'static>() {
                        use core::any::TypeId;
                        static mut LAST_TYPE: Option<TypeId> = None;
                        unsafe {
                            assert!(! cfg!(target_feature = "atomics"));
                            let id = TypeId::of::<T>();
                            match LAST_TYPE {
                                Some(ty) => {
                                    assert!(
                                        ty == id, "cannot use two types with this resource type"
                                    )
                                }
                                None => LAST_TYPE = Some(id),
                            }
                        }
                    }
                    #[doc(hidden)]
                    pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
                        Self::type_guard::<T>();
                        let _ = unsafe {
                            _rt::Box::from_raw(handle as *mut _ActorRep<T>)
                        };
                    }
                    fn as_ptr<T: GuestActor>(&self) -> *mut _ActorRep<T> {
                        Actor::type_guard::<T>();
                        T::_resource_rep(self.handle()).cast()
                    }
                }
                /// A borrowed version of [`Actor`] which represents a borrowed value
                /// with the lifetime `'a`.
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct ActorBorrow<'a> {
                    rep: *mut u8,
                    _marker: core::marker::PhantomData<&'a Actor>,
                }
                impl<'a> ActorBorrow<'a> {
                    #[doc(hidden)]
                    pub unsafe fn lift(rep: usize) -> Self {
                        Self {
                            rep: rep as *mut u8,
                            _marker: core::marker::PhantomData,
                        }
                    }
                    /// Gets access to the underlying `T` in this resource.
                    pub fn get<T: GuestActor>(&self) -> &T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    fn as_ptr<T: 'static>(&self) -> *mut _ActorRep<T> {
                        Actor::type_guard::<T>();
                        self.rep.cast()
                    }
                }
                unsafe impl _rt::WasmResource for Actor {
                    #[inline]
                    unsafe fn drop(_handle: u32) {
                        #[cfg(not(target_arch = "wasm32"))]
                        unreachable!();
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]hive:actor/actor@0.1.0"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-drop]actor"]
                                fn drop(_: u32);
                            }
                            unsafe { drop(_handle) };
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_constructor_actor_cabi<T: GuestActor>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = Actor::new(T::new(_rt::string_lift(bytes0)));
                    (result1).take_handle() as i32
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_actor_handle_message_cabi<T: GuestActor>(
                    arg0: *mut u8,
                    arg1: *mut u8,
                    arg2: usize,
                    arg3: *mut u8,
                    arg4: usize,
                    arg5: *mut u8,
                    arg6: usize,
                    arg7: *mut u8,
                    arg8: usize,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
                    let len1 = arg4;
                    let bytes1 = _rt::Vec::from_raw_parts(arg3.cast(), len1, len1);
                    let len2 = arg6;
                    let bytes2 = _rt::Vec::from_raw_parts(arg5.cast(), len2, len2);
                    let len3 = arg8;
                    T::handle_message(
                        unsafe { ActorBorrow::lift(arg0 as u32 as usize) }.get(),
                        MessageEnvelope {
                            message_type: _rt::string_lift(bytes0),
                            from_actor_id: _rt::string_lift(bytes1),
                            from_scope: _rt::string_lift(bytes2),
                            payload: _rt::Vec::from_raw_parts(arg7.cast(), len3, len3),
                        },
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_actor_destructor_cabi<T: GuestActor>(
                    arg0: *mut u8,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    T::destructor(
                        unsafe { ActorBorrow::lift(arg0 as u32 as usize) }.get(),
                    );
                }
                pub trait Guest {
                    type Actor: GuestActor;
                }
                pub trait GuestActor: 'static {
                    #[doc(hidden)]
                    unsafe fn _resource_new(val: *mut u8) -> u32
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = val;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]hive:actor/actor@0.1.0"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-new]actor"]
                                fn new(_: *mut u8) -> u32;
                            }
                            unsafe { new(val) }
                        }
                    }
                    #[doc(hidden)]
                    fn _resource_rep(handle: u32) -> *mut u8
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = handle;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]hive:actor/actor@0.1.0"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-rep]actor"]
                                fn rep(_: u32) -> *mut u8;
                            }
                            unsafe { rep(handle) }
                        }
                    }
                    /// Called by the host once when the actor is first instantiated.
                    /// Use this to initialize the actor's state.
                    /// @param scope - The execution scope provided by the host.
                    fn new(scope: _rt::String) -> Self;
                    /// The primary entry point for processing incoming messages. This
                    /// function is called by the host whenever another actor broadcasts
                    /// a message to the system.
                    /// @param message - The incoming message envelope, containing the
                    /// payload and sender's context.
                    fn handle_message(&self, message: MessageEnvelope) -> ();
                    /// Called by the host when the actor instance is being shut down.
                    /// Use this for cleanup tasks like persisting state.
                    fn destructor(&self) -> ();
                }
                #[doc(hidden)]
                macro_rules! __export_hive_actor_actor_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "hive:actor/actor@0.1.0#[constructor]actor")] unsafe extern "C"
                        fn export_constructor_actor(arg0 : * mut u8, arg1 : usize,) ->
                        i32 { unsafe { $($path_to_types)*::
                        _export_constructor_actor_cabi::<<$ty as $($path_to_types)*::
                        Guest >::Actor > (arg0, arg1) } } #[unsafe (export_name =
                        "hive:actor/actor@0.1.0#[method]actor.handle-message")] unsafe
                        extern "C" fn export_method_actor_handle_message(arg0 : * mut u8,
                        arg1 : * mut u8, arg2 : usize, arg3 : * mut u8, arg4 : usize,
                        arg5 : * mut u8, arg6 : usize, arg7 : * mut u8, arg8 : usize,) {
                        unsafe { $($path_to_types)*::
                        _export_method_actor_handle_message_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::Actor > (arg0, arg1, arg2, arg3,
                        arg4, arg5, arg6, arg7, arg8) } } #[unsafe (export_name =
                        "hive:actor/actor@0.1.0#[method]actor.destructor")] unsafe extern
                        "C" fn export_method_actor_destructor(arg0 : * mut u8,) { unsafe
                        { $($path_to_types)*::
                        _export_method_actor_destructor_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::Actor > (arg0) } } const _ : () = {
                        #[doc(hidden)] #[unsafe (export_name =
                        "hive:actor/actor@0.1.0#[dtor]actor")] #[allow(non_snake_case)]
                        unsafe extern "C" fn dtor(rep : * mut u8) { unsafe {
                        $($path_to_types)*:: Actor::dtor::< <$ty as $($path_to_types)*::
                        Guest >::Actor > (rep) } } }; };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_hive_actor_actor_0_1_0_cabi;
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    use core::fmt;
    use core::marker;
    use core::sync::atomic::{AtomicU32, Ordering::Relaxed};
    /// A type which represents a component model resource, either imported or
    /// exported into this component.
    ///
    /// This is a low-level wrapper which handles the lifetime of the resource
    /// (namely this has a destructor). The `T` provided defines the component model
    /// intrinsics that this wrapper uses.
    ///
    /// One of the chief purposes of this type is to provide `Deref` implementations
    /// to access the underlying data when it is owned.
    ///
    /// This type is primarily used in generated code for exported and imported
    /// resources.
    #[repr(transparent)]
    pub struct Resource<T: WasmResource> {
        handle: AtomicU32,
        _marker: marker::PhantomData<T>,
    }
    /// A trait which all wasm resources implement, namely providing the ability to
    /// drop a resource.
    ///
    /// This generally is implemented by generated code, not user-facing code.
    #[allow(clippy::missing_safety_doc)]
    pub unsafe trait WasmResource {
        /// Invokes the `[resource-drop]...` intrinsic.
        unsafe fn drop(handle: u32);
    }
    impl<T: WasmResource> Resource<T> {
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
            debug_assert!(handle != u32::MAX);
            Self {
                handle: AtomicU32::new(handle),
                _marker: marker::PhantomData,
            }
        }
        /// Takes ownership of the handle owned by `resource`.
        ///
        /// Note that this ideally would be `into_handle` taking `Resource<T>` by
        /// ownership. The code generator does not enable that in all situations,
        /// unfortunately, so this is provided instead.
        ///
        /// Also note that `take_handle` is in theory only ever called on values
        /// owned by a generated function. For example a generated function might
        /// take `Resource<T>` as an argument but then call `take_handle` on a
        /// reference to that argument. In that sense the dynamic nature of
        /// `take_handle` should only be exposed internally to generated code, not
        /// to user code.
        #[doc(hidden)]
        pub fn take_handle(resource: &Resource<T>) -> u32 {
            resource.handle.swap(u32::MAX, Relaxed)
        }
        #[doc(hidden)]
        pub fn handle(resource: &Resource<T>) -> u32 {
            resource.handle.load(Relaxed)
        }
    }
    impl<T: WasmResource> fmt::Debug for Resource<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("Resource").field("handle", &self.handle).finish()
        }
    }
    impl<T: WasmResource> Drop for Resource<T> {
        fn drop(&mut self) {
            unsafe {
                match self.handle.load(Relaxed) {
                    u32::MAX => {}
                    other => T::drop(other),
                }
            }
        }
    }
    pub use alloc_crate::boxed::Box;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_actor_world_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::hive::actor::actor::__export_hive_actor_actor_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::hive::actor::actor);
    };
}
#[doc(inline)]
pub(crate) use __export_actor_world_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:execute-bash:actor@0.1.0:actor-world:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 508] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xfa\x02\x01A\x02\x01\
A\x04\x01B\x03\x01p}\x01@\x02\x0cmessage-types\x07payload\0\x01\0\x04\0\x09broad\
cast\x01\x01\x03\0\x1ahive:actor/messaging@0.1.0\x05\0\x01B\x0c\x01p}\x01r\x04\x0c\
message-types\x0dfrom-actor-ids\x0afrom-scopes\x07payload\0\x04\0\x10message-env\
elope\x03\0\x01\x04\0\x05actor\x03\x01\x01i\x03\x01@\x01\x05scopes\0\x04\x04\0\x12\
[constructor]actor\x01\x05\x01h\x03\x01@\x02\x04self\x06\x07message\x02\x01\0\x04\
\0\x1c[method]actor.handle-message\x01\x07\x01@\x01\x04self\x06\x01\0\x04\0\x18[\
method]actor.destructor\x01\x08\x04\0\x16hive:actor/actor@0.1.0\x05\x01\x04\0$ex\
ecute-bash:actor/actor-world@0.1.0\x04\0\x0b\x11\x01\0\x0bactor-world\x03\0\0\0G\
\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen\
-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
