[package]
name = "buildable_simple"
version = "0.1.0"
edition = "2021"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.43"

[package.metadata.component.target.dependencies]
"hive:actor" = { path = "../../../hive_actor_bindings/wit" }