[model]
name = "accounts/fireworks/models/qwen3-235b-a22b"
endpoint = "https://api.fireworks.ai/inference/v1/"
system_prompt = "You are a helpful assistant. Focus on executing quickly and accurately and responding succinctly and accurately."
adapater = "OpenAI"
auth = "FIREWORKS_API_KEY" 


[mcp_servers.github]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-github"]

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest", "--browser", "brave"]

[key_bindings]
clear_default = false

[key_bindings.bindings]
"cmd-alt-w" = "CaptureWindow"
"cmd-alt-y" = "CaptureClipboard"
"cmd-alt-a" = "Assist"
"cmd-alt-m" = "ToggleRecordMicrophone"
