# Example configuration showing how to use Jinja templates for system prompts

# Commands that can be executed without user confirmation
whitelisted_commands = [
    "ls",
    "pwd", 
    "echo",
    "cat",
    "grep",
    "git",
    "cargo",
    "npm",
    "node",
    "python",
]

[model]
name = "accounts/fireworks/models/qwen3-235b-a22b"
endpoint = "https://api.fireworks.ai/inference/v1/"

# Example of a Jinja template system prompt
# This template will be rendered with context about available tools, system info, etc.
system_prompt = """You are an AI coding assistant running on {{ os }} ({{ arch }}).

Current time: {{ current_datetime }}

You have access to the following {{ tools|length }} tools:
{% for tool in tools -%}
- **{{ tool.name }}**: {{ tool.description }}
{% endfor %}

{% if whitelisted_commands -%}
The following commands can be executed without user confirmation:
{{ whitelisted_commands|join(', ') }}
{% endif %}

When helping with coding tasks:
1. Use the file_reader tool to understand existing code before making changes
2. Use the edit_file tool to make precise edits to files
3. Use the command tool to run tests, builds, or other development commands
4. Use the planner tool for complex multi-step tasks

Always think step-by-step and use tools appropriately to accomplish the user's goals.
"""

adapater = "OpenAI"
auth = "FIREWORKS_API_KEY"

# MCP servers configuration
[mcp_servers.github]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-github"]

# Key bindings configuration
[key_bindings]
clear_defaults = false

[key_bindings.bindings]
"cmd-alt-w" = "CaptureWindow"
"cmd-alt-y" = "CaptureClipboard"
"cmd-alt-a" = "Assist"
"cmd-alt-m" = "ToggleRecordMicrophone"
"ctrl-c" = "Exit"