[package]
name = "report_normal"
version = "0.1.0"
edition.workspace = true
license.workspace = true
description = "Status reporting actor for normal agent workflow updates"
repository.workspace = true
readme.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wasmind_actor_utils.workspace = true
serde.workspace = true  
serde_json = "1"
wit-bindgen-rt.workspace = true

[package.metadata.component.target.dependencies]
"wasmind:actor" = { path = "../../../../crates/wasmind_actor_bindings/wit" }